#change this to your own repo, should you have uploaded your image!
FROM  quasarframework/client-dev:latest

MAINTAINER Your Name <your.email@your-sites-address.com>

WORKDIR /opt/app

COPY package.json /opt/app/

RUN apk --update add tar
RUN apk add curl
RUN curl -o- -L https://yarnpkg.com/install.sh | bash
RUN export PATH="$HOME/.yarn/bin:$PATH" && yarn

COPY . /opt/app

EXPOSE 8080

CMD /bin/sh
